### ISSUE TITLE
期待需求

### ISSUE THREAD

**Issue by qbb-dev** [diwand/YapiIdeaUploadPlugin#1]
## 如果觉得目前插件有任何需要改进的地方或者未满足的需求 请在这里留言

**Comment by qbb-dev** [comment]
1:支持 xxxMapping value 为空情况 [已支持]
2:支持 RequestParam 备注从注释中获取 [已支持]
3:支持 notnull 分组
4:支持其他校验参数注解 比如NotBlank

**Comment by smileyao** [comment]
参数String注解NotBlank时，希望能识别为必填

**Comment by qbb-dev** [comment]
> 参数String注解NotBlank时，希望能识别为必填

下个版本1.6.8支持

**Comment by xiaoyuervae** [comment]
新版本的idea 是不是不支持啊  一直显示please check config,[projectToken,projectId,yapiUrl,projectType]

**Comment by qbb-dev** [comment]
> 新版本的idea 是不是不支持啊 一直显示please check config,[projectToken,projectId,yapiUrl,projectType]

请提供下版本，和当前的配置

**Comment by qbb-dev** [comment]
> > 参数String注解NotBlank时，希望能识别为必填
> 
> 下个版本1.6.8支持

推迟一个版本支持

**Comment by swuzjb** [comment]
期待一个 当接口已存在不更新的配置项，以免一些修改被覆盖。

**Comment by JackyLeeCS** [comment]
期望支持kotlin

**Comment by JackyLeeCS** [comment]
> 期望支持kotlin

现在会报异常
```
java.lang.NullPointerException
	at com.qbb.build.BuildJsonForYapi.actionPerformedList(BuildJsonForYapi.java:80)
	at com.qbb.interaction.UploadToYapi.actionPerformed(UploadToYapi.java:118)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:107)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:524)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:546)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by 820229268** [comment]
期待对 get请求 参数是一个实体Bean的支持

**Comment by swuzjb** [comment]
目前插架对Integer 包装类上传后的类型 也为 Integer  但是 yapi的定义是 integer  需要特殊处理下

**Comment by xujiamingpython** [comment]
3：支持notnull分组 现在支持了吗？

**Comment by Sparkinzy** [comment]
期望支持php , 注解格式如果能自定义的话，最好不过了！目前使用的是apidoc 的格式做的接口文档

**Comment by leeyongyao** [comment]
希望支持父类controller中的接口

**Comment by Planeswalker23** [comment]
希望在接口中加一个与@menu类型的注解，如@status，标志接口的完成状态。现在默认都是done。

**Comment by qbb-dev** [comment]
> 希望在接口中加一个与@menu类型的注解，如@status，标志接口的完成状态。现在默认都是done。

可行，下个版本支持

**Comment by qbb-dev** [comment]
> apidoc

很抱歉，php 不了解，如果需要请二次开发

**Comment by w420372197** [comment]
能否吧配置写到其他文件中, misc.xml 文件属于配置文件,不好提交

**Comment by qbb-dev** [comment]
> 能否吧配置写到其他文件中, misc.xml 文件属于配置文件,不好提交

为了就是不能提交,每个人的配置不一样，token 不一样

**Comment by lms-8023** [comment]
目前@menu加载类上的话不生效，因为在方法上没有单独设置@menu且方法优先级大于类，导致生成的Yapi文件夹为默认名称tool-temp。其次关于返回值使用@return并没有在Yapi中生成内容

**Comment by qbb-dev** [comment]
> 为在方法上没有单独设置@menu且方法优先级大于类，导致生成的Yapi文件夹为默认名称tool-temp。

请提供下版本和注释，正常结果是类上有@menu,方法没有回使用类上的，第二个问题，返回结果不是通过@return 决定的，是通过方法实际写的返回值决定

**Comment by lms-8023** [comment]
Dear


      感谢你的回复，在你的回复中@menu所说的版本是什么版本呢。

代码如下：类顶部注释，放在了package的上边
/**
 * @Title: Test.java
 * @Description: Test
 * <p>
 * Copyright(C) 2018-2019    Test
 * Company:   Test
 * @menu Test
 * @author lms
 * @version V1.0
 * @Date: 10:33 2019/7/12
 * <p>
 * 修改历史:
 * Date                 Author        Version        Description
 * -----------------------------------------------------------------------------------
 * 10:33 2019/7/12       lms        1.0            初始化版本
 */
    关于返回值，最终return了一个以下对象：
public SuccessMsg(Object data) {
    this.success = true;
    this.message = "成功";
    this.data = data;
}
但是在Yapi是以下样子：



有劳还望解惑




------------------ 原始邮件 ------------------
发件人: "亲宝宝"<notifications@github.com>;
发送时间: 2019年8月6日(星期二) 下午5:17
收件人: "diwand/YapiIdeaUploadPlugin"<YapiIdeaUploadPlugin@noreply.github.com>;
抄送: "后知后觉"<959996367@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [diwand/YapiIdeaUploadPlugin] 期待需求 (#1)



 
为在方法上没有单独设置@menu且方法优先级大于类，导致生成的Yapi文件夹为默认名称tool-temp。
  
请提供下版本和注释，正常结果是类上有@menu,方法没有回使用类上的，第二个问题，返回结果不是通过@return 决定的，是通过方法实际写的返回值决定

**Comment by qbb-dev** [comment]
> public SuccessMsg(Object data) { this.success = true; this.message = "成功"; this.data = data; }

我使用插件版本1.7.1 尝试复现您的@men问题，很抱歉没有复现，能正常创建菜单，并且接口归属于Test 下，关于第二个问题您贴的图似乎有问题。如果可以请加qq群644642474 ，然后@Ernest,会给你解答

**Comment by lms-8023** [comment]
好的，谢谢。已经进群       




------------------ 原始邮件 ------------------
发件人: "亲宝宝"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 下午5:04
收件人: "diwand/YapiIdeaUploadPlugin"<YapiIdeaUploadPlugin@noreply.github.com>;
抄送: "后知后觉"<959996367@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [diwand/YapiIdeaUploadPlugin] 期待需求 (#1)



 
public SuccessMsg(Object data) { this.success = true; this.message = "成功"; this.data = data; }
  
我使用插件版本1.7.1 尝试复现您的@men问题，很抱歉没有复现，能正常创建菜单，并且接口归属于Test 下，关于第二个问题您贴的图似乎有问题。如果可以请加qq群644642474 ，然后@ernest,会给你解答

**Comment by csman7117** [comment]
notblank注解 还是没起作用，notnull分组 没起作用
插件版本: 1.7.2
bean注释：
    
    @NotNull(groups = {UpdateGroup.class}, message = "主键不能为空")
    private String id;


    @NotBlank(groups = {AddGroup.class}, message = "运营服务公司全称为空")
    private String companyName;

**Comment by qbb-dev** [comment]
> notblank注解 还是没起作用，notnull分组 没起作用
> 插件版本: 1.7.2
> bean注释：
> 
> ```
> @NotNull(groups = {UpdateGroup.class}, message = "主键不能为空")
> private String id;
> 
> 
> @NotBlank(groups = {AddGroup.class}, message = "运营服务公司全称为空")
> private String companyName;
> ```

暂时还没支持

**Comment by scofier** [comment]
希望支持枚举类型的识别

**Comment by qbb-dev** [comment]
> 希望支持枚举类型的识别

请具体说明

**Comment by scofier** [comment]
> > 希望支持枚举类型的识别
> 
> 请具体说明

类似下面定义的枚举， 现在是需要在注释里面把枚举值MAIL、FEMAIL都写在注释里面，希望能自动识别，比如： MAIL: 男性，FEMAIL: 女性。 

```
/**
 * 性别 枚举
 */
public enum SexEnum {
    /**
     * 男性
     */
    MALE(0),
    /**
     * 女性
     */
    FEMALE(1);

    Integer value;
```

**Comment by qbb-dev** [comment]
> > > 希望支持枚举类型的识别
> > 
> > 
> > 请具体说明
> 
> 类似下面定义的枚举， 现在是需要在注释里面把枚举值MAIL、FEMAIL都写在注释里面，希望能自动识别，比如： MAIL: 男性，FEMAIL: 女性。
> 
> ```
> /**
>  * 性别 枚举
>  */
> public enum SexEnum {
>     /**
>      * 男性
>      */
>     MALE(0),
>     /**
>      * 女性
>      */
>     FEMALE(1);
> 
>     Integer value;
> ```

ok,后面支持

**Comment by ac3than** [comment]
建议: 能否容错一下 @RequestMapping 开头没加斜线的情况, 因为项目中, 有的类或者方法 类似 `@RequestMapping("add") `这种, 即没有斜线开头, 访问接口时, springmvc 框架是会自动帮我们处理这种, 想问下 yapi upload 插件能否帮忙判断如果没有斜线, 那么自动在开头添加斜线功能

**Comment by qbb-dev** [comment]
> 建议: 能否容错一下 @RequestMapping 开头没加斜线的情况, 因为项目中, 有的类或者方法 类似 `@RequestMapping("add") `这种, 即没有斜线开头, 访问接口时, springmvc 框架是会自动帮我们处理这种, 想问下 yapi upload 插件能否帮忙判断如果没有斜线, 那么自动在开头添加斜线功能

好，后面支持

**Comment by qbb-dev** [comment]
> > 建议: 能否容错一下 @RequestMapping 开头没加斜线的情况, 因为项目中, 有的类或者方法 类似 `@RequestMapping("add") `这种, 即没有斜线开头, 访问接口时, springmvc 框架是会自动帮我们处理这种, 想问下 yapi upload 插件能否帮忙判断如果没有斜线, 那么自动在开头添加斜线功能
> 
> 好，后面支持

从1.7.5 开始支持

**Comment by ac3than** [comment]
> > > 建议: 能否容错一下 @RequestMapping 开头没加斜线的情况, 因为项目中, 有的类或者方法 类似 `@RequestMapping("add") `这种, 即没有斜线开头, 访问接口时, springmvc 框架是会自动帮我们处理这种, 想问下 yapi upload 插件能否帮忙判断如果没有斜线, 那么自动在开头添加斜线功能
> > 
> > 
> > 好, 后面支持
> 
> 从 1.7.5 开始支持

收到, 谢谢

**Comment by daokunzhu1107** [comment]
可以支持swagger格式的注释么

**Comment by qbb-dev** [comment]
> 可以支持swagger格式的注释么

暂不支持

**Comment by 24kpure** [comment]
考虑下提供下swagger基础注解？

**Comment by xlj44400** [comment]
怎么不支持 idea 2019.3版本

**Comment by ciweigg2** [comment]
Yapiupload插件可以支持读取引用依赖架包的注释吗

**Comment by astali** [comment]
> > 新版本的idea 是不是不支持啊 一直显示please check config,[projectToken,projectId,yapiUrl,projectType]
> 
> 请提供下版本，和当前的配置

IDEA 2018.2 配置多模块会出现该情况

**Comment by qbb-dev** [comment]
> > > 新版本的idea 是不是不支持啊 一直显示please check config,[projectToken,projectId,yapiUrl,projectType]
> > 
> > 
> > 请提供下版本，和当前的配置
> 
> IDEA 2018.2 配置多模块会出现该情况

1.7.4以上多模块配置不一样，请看文档

**Comment by wbean** [comment]
期待支持一下pash 配置,现在上传的pash 是自动生成的.期待有个注解可以指定方法的path
之所以提这个需求是因为工程提供的接口是需要客户端通过网关接入的, 而网关对客户端暴露的接口地址是自定义的.

**Comment by qbb-dev** [comment]
> 期待支持一下pash 配置,现在上传的pash 是自动生成的.期待有个注解可以指定方法的path
> 之所以提这个需求是因为工程提供的接口是需要客户端通过网关接入的, 而网关对客户端暴露的接口地址是自定义的.

明白你的需求，放在1.7.8 后加入

**Comment by VangelisHaha** [comment]
> 非常感谢有这样的工具让我司更加快速的创建接口，这真的非常棒。但是我司有一些自动化接口的需求，希望我们在接口文档中**备注出**去添加`请求json示例`和`返回json示例` 
![image](https://user-images.githubusercontent.com/33385286/71861938-0ed2a380-3133-11ea-99cb-468a56ab986a.png)
可否支持针对于图上备注信息的定制呢？非常感谢作者的开源。

**Comment by qbb-dev** [comment]
> > 非常感谢有这样的工具让我司更加快速的创建接口，这真的非常棒。但是我司有一些自动化接口的需求，希望我们在接口文档中**备注出**去添加`请求json示例`和`返回json示例`
> > ![image](https://user-images.githubusercontent.com/33385286/71861938-0ed2a380-3133-11ea-99cb-468a56ab986a.png)
> > 可否支持针对于图上备注信息的定制呢？非常感谢作者的开源。
很抱歉，图裂了，可以重新上传试试吗？或者可以加群qq644642474 @Ernest

**Comment by VangelisHaha** [comment]
> > > 非常感谢有这样的工具让我司更加快速的创建接口，这真的非常棒。但是我司有一些自动化接口的需求，我们希望在接口文档中**备注出**去添加`请求json示例`状语从句：
> > > 可否请立即获取iTunes针对于图产品上备注信息的定制呢？非常感谢作者的开源。
> > > 很抱歉，图裂了，可以重新上传试试吗？或者可以加群qq644642474 @ernest`返回json示例`
> > > ![图片](https://user-images.githubusercontent.com/33385286/71861938-0ed2a380-3133-11ea-99cb-468a56ab986a.png)


期望结果：
![image-20200108192903222](https://vangelis-blog.oss-cn-beijing.aliyuncs.com/weixin/2020-01-08-112903.png)

图中备注处可以通过一定方式支持定制，而不是默认方法的代码
![image-20200108193159595](https://vangelis-blog.oss-cn-beijing.aliyuncs.com/weixin/2020-01-08-113159.png)

**Comment by VangelisHaha** [comment]
![image-20200108193159595](https://vangelis-blog.oss-cn-beijing.aliyuncs.com/weixin/2020-01-08-113159.png)

**Comment by VangelisHaha** [comment]
现状
![2](https://user-images.githubusercontent.com/33385286/71974977-dd022f80-324d-11ea-8dbd-aeea4f9b8408.png)

期望
![1](https://user-images.githubusercontent.com/33385286/71974984-e12e4d00-324d-11ea-91c6-451fffdda057.png)

**Comment by VangelisHaha** [comment]
![](https://user-images.githubusercontent.com/33385286/71975093-1a66bd00-324e-11ea-93fd-77294fc1d8b3.png)

**Comment by VangelisHaha** [comment]
@ernest  两个群都显示无法加入，图上的内容就是Yapi文档接口详情页面的***备注*** 栏 中的文字，是否支持一定方式进行定制

**Comment by qbb-dev** [comment]
> > > > 非常感谢有这样的工具让我司更加快速的创建接口，这真的非常棒。但是我司有一些自动化接口的需求，我们希望在接口文档中**备注出**去添加`请求json示例`状语从句：
> > > > 可否请立即获取iTunes针对于图产品上备注信息的定制呢？非常感谢作者的开源。
> > > > 很抱歉，图裂了，可以重新上传试试吗？或者可以加群qq644642474 @ernest`返回json示例`
> > > > ![图片](https://user-images.githubusercontent.com/33385286/71861938-0ed2a380-3133-11ea-99cb-468a56ab986a.png)
> 
> 期望结果：
> ![image-20200108192903222](https://camo.githubusercontent.com/203f04df2a8409d1e04166f02b629875540c8bd3/68747470733a2f2f76616e67656c69732d626c6f672e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f77656978696e2f323032302d30312d30382d3131323930332e706e67)
> 
> 图中备注处可以通过一定方式支持定制，而不是默认方法的代码
> ![image-20200108193159595](https://camo.githubusercontent.com/a096365a58758b40f23b96fcfefcf3fc50f759ea/68747470733a2f2f76616e67656c69732d626c6f672e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f77656978696e2f323032302d30312d30382d3131333135392e706e67)

看到图了，请问下需要使用json 的场景为？ 这个改动比较大

**Comment by qbb-dev** [comment]
> > 期待支持一下pash 配置,现在上传的pash 是自动生成的.期待有个注解可以指定方法的path
> > 之所以提这个需求是因为工程提供的接口是需要客户端通过网关接入的, 而网关对客户端暴露的接口地址是自定义的.
> 
> 明白你的需求，放在1.7.8 后加入

1.7.8 已经上线

**Comment by boommanpro** [comment]
默认给出的参数示例不好用, 希望可以从注释上获取参数示例.

**Comment by boommanpro** [comment]
现在接口的备注 我看到是取得@RequestMapping 附近的代码,如果我手动添加了一些内容,在下一次更新接口的时候会覆盖掉,如何只覆盖前面部分,不覆盖后面的

**Comment by qbb-dev** [comment]
> 现在接口的备注 我看到是取得@RequestMapping 附近的代码,如果我手动添加了一些内容,在下一次更新接口的时候会覆盖掉,如何只覆盖前面部分,不覆盖后面的

需要yapi 是carzy 分支的，官方版本的yapi 不支持

**Comment by swxu2005** [comment]
希望能支持 Map<String, Object> 类型的参数。由开发人员在注释中写明每个参数的意义

**Comment by swxu2005** [comment]
希望能支持Jackson的字段忽略注解：
@JsonIgnore和@JsonProperty(access = JsonProperty.Access.READ_ONLY)等

**Comment by mengTnT** [comment]
需求背景：每次修改完代码，比如改了注释，改了参数，都要手动提交一下文档到yapi,很麻烦，有时候
还会忘记。
具体需求：git上代码版本改变时，触发更新文档到yapi
十分感谢🙏

**Comment by wuwh3** [comment]
自动上传未识别@Api(value = "xx信息管理", description = "xx信息管理", tags = "xx信息管理")
标签管理的内容，直接以Controller类名作为分类名了，期望支持识别@Api

**Comment by Veiasai** [comment]
你好 有没有可能支持在注释中写mock.js的定义？能够定义yapi的mock数据？
现在需要手动上yapi界面书写，但接口更新时会比较麻烦。

ps: 看了下代码发现已经支持
#63

**Comment by wapmnw** [comment]
需求背景：请求参数的实体类是通过参数解析器注入的，这种是不需要写进请求参数。
![image](https://user-images.githubusercontent.com/31203438/81934618-d59aca80-9621-11ea-9abc-2fb82574a786.png)


期望需求：希望能实现参数屏蔽，不进行上传到请求参数中，对参数是否必须可以设置

**Comment by HackenPai** [comment]
如果在yapi后台配置了多个project时，使用插件上传API，默认只会上传到第一个project中，希望增加指定模块分别上传到指定project中

**Comment by yubaogu** [comment]
增加指定字段过滤，有的字段接口中需要，但是暴露的是用作上下文处理，并不需要暴露再文档中

**Comment by xiongmingwu** [comment]
希望能统一配置公共的http head,比如说鉴权的场景需要传入token,但现在上传文档后，由于没地方输入token，导致无法在yapi上进行接口调试。

**Comment by FurionCS** [comment]
这个实现方案：建议通过yapi的请求脚本实现

发自我的iPhone

**Comment by Belep** [comment]
上传时期待加入，com.fasterxml.jackson.annotation.JsonProperty注解的支持。
因为有时候可能会别名，或是用下滑线字段显示。

**Comment by chen-gliu** [comment]
可以添加Spring WebFlux的支持吗

**Comment by zhangbokang** [comment]
期望可以支持springdata的Page【org.springframework.data.domain.Page】，目前idea好像无法支持类似【CommonResult<Page<TaskDto>>】这种的返回值的解析

**Comment by joeyFuck** [comment]
Map<String, Object> 类型的参数，怎么写注释呢？ 
现在map参数，生成文档后就一个参数 key

**Comment by ksfallen** [comment]
期望可以支持解析第三方jar包里的类字段注释,  当jar包有下载源码时是可以看到注释的

试了下 api-generator 这个插件是兼容第三方jar包

[可以参考下这个](https://github.com/Forgus/api-generator/blob/master/src/site/forgus/plugins/apigenerator/normal/FieldInfo.java)

**Comment by chimmhuang** [comment]
该类个别属性有doc注释，但是不需要上传到 yapi 的这种功能希望能拥有。

**Comment by nickevin** [comment]
希望支持按项目级别（所有的类、类中的方法）上传。

**Comment by AresKingCarry** [comment]
希望支持grpc接口文档上传
