### ISSUE TITLE
2.0.4-bug-2-npe

### ISSUE THREAD

**Issue by herongyun** [diwand/YapiIdeaUploadPlugin#111]
## 版本号
~ 2.0.4-bug-2-控制住异常

## 什么问题
~java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at com.redsoft.idea.plugin.yapiv2.req.abs.AbstractCompoundRequestParamResolver.resolvePojo(AbstractCompoundRequestParamResolver.java:98)
	at com.redsoft.idea.plugin.yapiv2.req.abs.AbstractCompoundRequestParamResolver.doResolverItem(AbstractCompoundRequestParamResolver.java:43)
	at com.redsoft.idea.plugin.yapiv2.req.EachRequestParamResolver.lambda$doResolve$0(EachRequestParamResolver.java:19)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.redsoft.idea.plugin.yapiv2.req.EachRequestParamResolver.doResolve(EachRequestParamResolver.java:19)
	at com.redsoft.idea.plugin.yapiv2.req.abs.AbstractRequestParamResolver.resolve(AbstractRequestParamResolver.java:24)
	at com.redsoft.idea.plugin.yapiv2.req.impl.RequestResolverImpl.lambda$resolve$0(RequestResolverImpl.java:29)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at com.redsoft.idea.plugin.yapiv2.req.impl.RequestResolverImpl.resolve(RequestResolverImpl.java:29)
	at com.redsoft.idea.plugin.yapiv2.api.impl.ApiResolverImpl.resolve(ApiResolverImpl.java:76)
	at com.redsoft.idea.plugin.yapiv2.parser.impl.PsiMethodParserImpl.parse(PsiMethodParserImpl.java:28)
	at com.redsoft.idea.plugin.yapiv2.parser.impl.PsiClassParserImpl.lambda$parse$0(PsiClassParserImpl.java:33)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.redsoft.idea.plugin.yapiv2.parser.impl.PsiClassParserImpl.parse(PsiClassParserImpl.java:34)
	at com.redsoft.idea.plugin.yapiv2.parser.YApiParser.parse(YApiParser.java:59)
	at com.redsoft.idea.plugin.yapiv2.action.YApiUploadAction.actionPerformed(YApiUploadAction.java:52)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:622)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:671)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:518)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:473)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:223)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:653)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
2019.1.3

**Comment by 24kpure** [comment]
more info，show your controller detail

**Comment by aqiu202** [comment]
你这个应该是针对我的插件的问题，不是这个仓库，应该是这个[RedsoftYapiUpload](https://github.com/aqiu202/RedsoftYapiUpload) ~OzO

**Comment by aqiu202** [comment]
> ## 版本号
> ~ 2.0.4-bug-2-控制住异常
> 
> ## 什么问题
> ~java.lang.NullPointerException at java.util.Objects.requireNonNull(Objects.java:203) at com.redsoft.idea.plugin.yapiv2.req.abs.AbstractCompoundRequestParamResolver.resolvePojo(AbstractCompoundRequestParamResolver.java:98) at com.redsoft.idea.plugin.yapiv2.req.abs.AbstractCompoundRequestParamResolver.doResolverItem(AbstractCompoundRequestParamResolver.java:43) at com.redsoft.idea.plugin.yapiv2.req.EachRequestParamResolver.lambda$doResolve$0(EachRequestParamResolver.java:19) at java.util.ArrayList.forEach(ArrayList.java:1257) at com.redsoft.idea.plugin.yapiv2.req.EachRequestParamResolver.doResolve(EachRequestParamResolver.java:19) at com.redsoft.idea.plugin.yapiv2.req.abs.AbstractRequestParamResolver.resolve(AbstractRequestParamResolver.java:24) at com.redsoft.idea.plugin.yapiv2.req.impl.RequestResolverImpl.lambda$resolve$0(RequestResolverImpl.java:29) at java.util.Arrays$ArrayList.forEach(Arrays.java:3880) at com.redsoft.idea.plugin.yapiv2.req.impl.RequestResolverImpl.resolve(RequestResolverImpl.java:29) at com.redsoft.idea.plugin.yapiv2.api.impl.ApiResolverImpl.resolve(ApiResolverImpl.java:76) at com.redsoft.idea.plugin.yapiv2.parser.impl.PsiMethodParserImpl.parse(PsiMethodParserImpl.java:28) at com.redsoft.idea.plugin.yapiv2.parser.impl.PsiClassParserImpl.lambda$parse$0(PsiClassParserImpl.java:33) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) at com.redsoft.idea.plugin.yapiv2.parser.impl.PsiClassParserImpl.parse(PsiClassParserImpl.java:34) at com.redsoft.idea.plugin.yapiv2.parser.YApiParser.parse(YApiParser.java:59) at com.redsoft.idea.plugin.yapiv2.action.YApiUploadAction.actionPerformed(YApiUploadAction.java:52) at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261) at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278) at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:622) at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$2(IdeKeyEventDispatcher.java:671) at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195) at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:670) at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:518) at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:473) at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:223) at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:653) at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373) at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205) at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> ## 如何复现此问题
> ~
> 
> ## 接口定义 (如果可以的话,请上传请求对象和响应对象)
> ~
> 
> ## idea 版本
> 2019.1.3

你这个应该是针对我的插件的问题，不是这个仓库，应该是这个[RedsoftYapiUpload](https://github.com/aqiu202/RedsoftYapiUpload) ~OzO
