### ISSUE TITLE
空指针异常

### ISSUE THREAD

**Issue by swuzjb** [diwand/YapiIdeaUploadPlugin#13]
## 版本号
~ 

## 什么问题
~
java.lang.NullPointerException
	at com.qbb.build.BuildJsonForYapi.actionPerformedList(BuildJsonForYapi.java:98)
	at com.qbb.interaction.UploadToYapi.actionPerformed(UploadToYapi.java:118)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:107)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:524)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:546)
	at java.awt.Component.processMouseEvent(Component.java:6550)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6315)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:739)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 
![image](https://user-images.githubusercontent.com/3627122/58846973-c42c0d00-86b3-11e9-9334-190c7c10d3ef.png)

**Comment by swuzjb** [comment]
另外，补充一个问题，如果 返回的实体有 循环的可能 需要特殊处理一下。现在会无限递归。

**Comment by swuzjb** [comment]
不支持 String[] 这样的返回值

**Comment by qbb-dev** [comment]
> 另外，补充一个问题，如果 返回的实体有 循环的可能 需要特殊处理一下。现在会无限递归。

嗯嗯，已知问题

**Comment by qbb-dev** [comment]
> 不支持 String[] 这样的返回值

后面支持

**Comment by qbb-dev** [comment]
> ## 版本号
> ~
> 
> ## 什么问题
> ~
> java.lang.NullPointerException
> at com.qbb.build.BuildJsonForYapi.actionPerformedList(BuildJsonForYapi.java:98)
> at com.qbb.interaction.UploadToYapi.actionPerformed(UploadToYapi.java:118)
> at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
> at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:292)
> at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
> at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:107)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
> at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
> at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
> at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
> at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
> at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:121)
> at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
> at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:524)
> at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
> at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:546)
> at java.awt.Component.processMouseEvent(Component.java:6550)
> at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
> at java.awt.Component.processEvent(Component.java:6315)
> at java.awt.Container.processEvent(Container.java:2239)
> at java.awt.Component.dispatchEventImpl(Component.java:4899)
> at java.awt.Container.dispatchEventImpl(Container.java:2297)
> at java.awt.Component.dispatchEvent(Component.java:4721)
> at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
> at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
> at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
> at java.awt.Container.dispatchEventImpl(Container.java:2283)
> at java.awt.Window.dispatchEventImpl(Window.java:2746)
> at java.awt.Component.dispatchEvent(Component.java:4721)
> at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:766)
> at java.awt.EventQueue.access$500(EventQueue.java:98)
> at java.awt.EventQueue$3.run(EventQueue.java:715)
> at java.awt.EventQueue$3.run(EventQueue.java:709)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
> at java.awt.EventQueue$4.run(EventQueue.java:739)
> at java.awt.EventQueue$4.run(EventQueue.java:737)
> at java.security.AccessController.doPrivileged(Native Method)
> at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
> at java.awt.EventQueue.dispatchEvent(EventQueue.java:736)
> at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
> at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:674)
> at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
> at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
> at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
> at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
> at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
> 
> ## 如何复现此问题
> ~
> 
> ## 接口定义 (如果可以的话,请上传请求对象和响应对象)
> ~
> ![image](https://user-images.githubusercontent.com/3627122/58846973-c42c0d00-86b3-11e9-9334-190c7c10d3ef.png)
> 
> ## idea 版本

这个请检查下注释是否规范，或者请提供响应定义

**Comment by swuzjb** [comment]
`    /** 是否参加标志，1：参加，其他：未参加 */
    @Getter @Setter
    private int joinFlag = VisitAppointmentPortalDTO.JoinFlag.no.ordinal();`
是这个枚举类型导致的么？
