### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by scofier** [diwand/YapiIdeaUploadPlugin#50]
## 版本号
1.7.4

## 什么问题
```
null
java.lang.StackOverflowError
	at com.qbb.build.BuildJsonForYapi.addFilePaths(BuildJsonForYapi.java:935)
	at com.qbb.build.BuildJsonForYapi.getCollect(BuildJsonForYapi.java:914)
	at com.qbb.build.BuildJsonForYapi.getField(BuildJsonForYapi.java:854)
	at com.qbb.build.BuildJsonForYapi.getFields(BuildJsonForYapi.java:718)
	at com.qbb.build.BuildJsonForYapi.getCollect(BuildJsonForYapi.java:912)
	at com.qbb.build.BuildJsonForYapi.getField(BuildJsonForYapi.java:854)
	at com.qbb.build.BuildJsonForYapi.getFields(BuildJsonForYapi.java:718)
	at com.qbb.build.BuildJsonForYapi.getCollect(BuildJsonForYapi.java:912)
	at com.qbb.build.BuildJsonForYapi.getField(BuildJsonForYapi.java:854)
	...

```

还有另外一个controller生成的时候报错：
```
null
java.lang.StackOverflowError
	at com.intellij.util.CachedValueBase.getUpToDateOrNull(CachedValueBase.java:107)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:214)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at com.intellij.psi.impl.ScopedClassHierarchy.getHierarchy(ScopedClassHierarchy.java:102)
	at com.intellij.psi.impl.ScopedClassHierarchy.getSuperClassSubstitutor(ScopedClassHierarchy.java:110)
	at com.intellij.psi.impl.JavaClassSupersImpl.getSuperSubstitutorWithCaching(JavaClassSupersImpl.java:114)
	at com.intellij.psi.impl.JavaClassSupersImpl.getSuperClassSubstitutor(JavaClassSupersImpl.java:74)
	at com.intellij.psi.impl.InheritanceImplUtil.isInheritor(InheritanceImplUtil.java:41)
	at com.intellij.psi.impl.compiled.ClsClassImpl.isInheritor(ClsClassImpl.java:512)
	at com.intellij.psi.util.PsiUtil.substituteType(PsiUtil.java:1108)
	at com.intellij.psi.util.PsiUtil.substituteTypeParameter(PsiUtil.java:1084)
	at com.intellij.psi.util.PsiUtil.extractIterableTypeParameter(PsiUtil.java:1064)
	at com.qbb.build.BuildJsonForYapi.getField(BuildJsonForYapi.java:850)
	at com.qbb.build.BuildJsonForYapi.getFields(BuildJsonForYapi.java:718)
	at com.qbb.build.BuildJsonForYapi.getCollect(BuildJsonForYapi.java:912)
	at com.qbb.build.BuildJsonForYapi.getField(BuildJsonForYapi.java:854)
	...
```

## 如何复现此问题
~ 

## 接口定义 (如果可以的话,请上传请求对象和响应对象)

~ 

## idea 版本
IntelliJ IDEA 2018.1.3 (Ultimate Edition)
Build #IU-181.4892.42, built on May 8, 2018

Subscription is active until January 7, 2020
JRE: 1.8.0_152-release-1136-b38 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.2

**Comment by qbb-dev** [comment]
请检查下，请求对象或者响应对象是否存在循环调用的情况

**Comment by qbb-dev** [comment]
1.7.5 解决
